Repository NCAR/geocat-examples, pull requests merged in 2020-11, with the labels that each got.

#259 Reopening dataonmap_10
  Plots/WRF/NCL_dataonmap_10.py
  Plots/WRF/README.rst
Labels: ready to merge

#293 Github actions build failures
  .github/workflows/build.yml
Labels: bug, ready to merge

#242 Wrf_zoom_1_2
  Plots/WRF/NCL_WRF_zoom_1_2.py
Labels: ready for review, ready to merge

#281 Colorbar extend and norm
  Plots/Colors/CB_Height.py
  Plots/Colors/CB_Rain.py
  Plots/Colors/CB_Temperature.py
  Plots/Contours/NCL_proj_1.py
  Plots/MapProjections/NCL_lcnative_1.py
  Plots/MapProjections/NCL_native_2.py
  Plots/MapProjections/NCL_proj_3.py
  Plots/MapProjections/NCL_sat_3.py
  Plots/Overlays/NCL_overlay_6.py
  Plots/Polygons/NCL_polyg_19.inactv
  Plots/Vectors/NCL_vector_1.py
Labels: ready for review

#289 wrf_interp_3
  Plots/WRF/NCL_wrf_interp_3.py
Labels: ready for review

#283 skewt_2_2
  Plots/Skew-T/NCL_skewt_2_2.py
Labels: ready for review
