Repository NCAR/geocat-examples, pull requests merged in 2020-09, with the labels that each got.

#228 Radar 1
  Plots/MapProjections/NCL_radar_1.py
Labels: ready to merge

#262 Fix RTD Build Issue
  .github/workflows/build.yml
  .rtd_conda_environment.yml
  Plots/CSV/README.rst
Labels: bug, high priority, ready for review

#251 lb_4
  Plots/Contours/NCL_lb_4.py
Labels: ready to merge

#249 xy_13
  Plots/XY/NCL_xy_13.py
Labels: ready to merge

#246 h_lat_6
  Plots/Contours/NCL_h_lat_6.py
Labels: ready to merge

#219 dev_2
  Plots/Panels/NCL_dev_2.py
Labels: ready to merge

#244 Regress 1
  Plots/Regression/NCL_regress_1.py
  Plots/Regression/README.rst
Labels: ready to merge

#199 dev_1
  Plots/Panels/NCL_dev_1.py
Labels: ready to merge

#189 mask_2
  Plots/Masking/NCL_mask_2.py
Labels: ready to merge

#187 panel_2
  Plots/Panels/NCL_panel_2.py
Labels: ready to merge

#185 scatter_1
  Plots/Scatter/NCL_scatter_1.py
Labels: ready to merge

#229 Updating vector projection with helper function
  Plots/Vectors/NCL_vector_3.py
Labels: high priority

#267 Replacing single character colors with their full color name
  Plots/Boxplots/NCL_box_1.py
  Plots/Contours/NCL_color_1.py
  Plots/Contours/NCL_conOncon_5.py
  Plots/Contours/NCL_conwomap_1.py
  Plots/Contours/NCL_conwomap_2.py
  Plots/Contours/NCL_conwomap_3.py
  Plots/Contours/NCL_eof_1_1.py
  Plots/Contours/NCL_lb_2.py
  Plots/Contours/NCL_lb_3.py
  Plots/Contours/NCL_lb_4.py
  Plots/Contours/NCL_polar_1_lg.py
  Plots/Contours/NCL_proj_1.py
  Plots/MapProjections/NCL_native_2.py
  Plots/MapProjections/NCL_proj_2_lg.py
  Plots/MapProjections/NCL_sat_1.py
  Plots/MapProjections/NCL_sat_2.py
  Plots/Meteograms/NCL_meteo_1.py
  Plots/Panels/NCL_panel_1.py
  Plots/Panels/NCL_panel_2.py
  Plots/Panels/NCL_panel_3.py
  Plots/Panels/NCL_panel_35.py
  Plots/Panels/NCL_panel_5.py
  Plots/Polygons/NCL_polyg_19.inactv
  Plots/Polygons/NCL_polyg_2.py
  Plots/Regression/NCL_regress_1.py
  Plots/Scatter/NCL_scatter_3.py
  Plots/Scatter/NCL_scatter_4.py
Labels: bug, ready to merge

#227 polyg_8_lbar
  Plots/Polygons/NCL_polyg_8_lbar.py
Labels: ready to merge

#261 panel_10
  Plots/Panels/NCL_panel_10.py
  Plots/WRF/NCL_dataonmap_10.py
  Plots/WRF/README.rst
Labels: enhancement, ready to merge

#274 Removes dataonmap_10 example from master branch
  Plots/WRF/NCL_dataonmap_10.py
  Plots/WRF/README.rst
Labels: bug, high priority, ready to merge

#278 Names lg subscript removal (#277)
  Plots/Contours/NCL_ce_3_1.py
  Plots/Contours/NCL_ce_3_2.py
  Plots/MapProjections/NCL_lcnative_1.py
  Plots/MapProjections/NCL_proj_2.py
  Plots/MapProjections/NCL_proj_3.py
Labels: low priority, ready for review

#276 Docs gen warning fix (#275)
  Plots/CSV/NCL_write_csv_1.py
  Plots/Colors/CB_Temperature.py
  Plots/Contours/NCL_polar_1.py
  Plots/Overlays/NCL_overlay_1.py
  Plots/Overlays/NCL_overlay_6.py
  Plots/Polygons/NCL_polyg_18.py
  Plots/Polygons/NCL_polyg_8_lbar.py
  Plots/Regression/NCL_regress_1.py
  Plots/Scatter/NCL_scatter_1.py
  Plots/Scatter/NCL_scatter_6.py
  Plots/Shapefiles/NCL_shapefiles_1.py
  Plots/Vectors/NCL_vector_3.py
Labels: low priority, ready for review
