Repository NCAR/geocat-examples, pull requests merged in 2021-02, with the labels that each got.

#304 Remove "Edit on Github" buttons from RTD builds
  _templates/breadcrumbs.html
  index.rst
  support.rst
Labels: ready for review

#213 Contributor updates for repo-specific documentation
  CONTRIBUTING.md
  INSTALLATION.md
  README.md
  template_script.py
Labels: documentation

#306 NCL_panel_9.py
  Plots/Panels/NCL_panel_9.py
Labels: ready to merge

#307 NCL_native_1.py
  Plots/MapProjections/NCL_native_1.py
Labels: ready for review

#309 NCL_maponly_1.py
  Plots/MapProjections/NCL_maponly_1.py
  Plots/MapProjections/NCL_native_1.py
Labels: ready for review
