Repository NCAR/geocat-examples, pull requests merged in 2022-02, with the labels that each got.

#421 Adding calendar_average example
  GeoCAT-comp-examples/matplotlib/calendar_average_example.py
Labels: ready for review

#424 Update `NCL_skewt_2_2` to have subtitle
  Plots/Skew-T/NCL_skewt_2_2.py
Labels: enhancement, ready for review

#422 Adding climatology_average example
  GeoCAT-comp-examples/matplotlib/climatology_average_example.py
Labels: ready for review

#427 Use mamba for CI
  .github/workflows/ci.yml
Labels: bug
